default_platform(:ios)

lane :release_to_testflight do
  app_store_connect_api_key(
    key_id: ENV['AUTHENTICATION_KEY_ID'],
    issuer_id: ENV['AUTHENTICATION_KEY_ISSUER_ID'],
    key_content: ENV['AUTHENTICATION_KEY_CONTENT'],
    in_house: false
  )
  auth_key_path = sh("pwd").gsub("\n",'') + "/../AuthKey.p8"
  build_app(
    scheme: "CloudSignedExample",
    configuration: "Release",
    export_method: "app-store",
    export_team_id: ENV['TEAM_ID'],
    include_bitcode: true,
    include_symbols: true,
    export_options: {
      "signingStyle" => "automatic",
      "manageAppVersionAndBuildNumber" => false
    },
    xcargs: "-allowProvisioningUpdates -authenticationKeyIssuerID #{ENV['AUTHENTICATION_KEY_ISSUER_ID']} -authenticationKeyID #{ENV['AUTHENTICATION_KEY_ID']} -authenticationKeyPath \"#{auth_key_path}\""
  )
  upload_to_testflight(
    skip_submission: true,
    skip_waiting_for_build_processing: true
  )
end

lane :release_to_ipa do
  app_store_connect_api_key(
    key_id: ENV['AUTHENTICATION_KEY_ID'],
    issuer_id: ENV['AUTHENTICATION_KEY_ISSUER_ID'],
    key_content: ENV['AUTHENTICATION_KEY_CONTENT'],
    in_house: false
  )
  auth_key_path = sh("pwd").gsub("\n",'') + "/../AuthKey.p8"
  build_app(
    scheme: "CloudSignedExample",
    configuration: "Release",
    export_method: "app-store",
    export_team_id: ENV['TEAM_ID'],
    include_bitcode: true,
    include_symbols: true,
    export_options: {
      "signingStyle" => "automatic",
      "manageAppVersionAndBuildNumber" => false
    },
    skip_codesigning: true,
    xcargs: "-allowProvisioningUpdates -authenticationKeyIssuerID #{ENV['AUTHENTICATION_KEY_ISSUER_ID']} -authenticationKeyID #{ENV['AUTHENTICATION_KEY_ID']} -authenticationKeyPath \"#{auth_key_path}\"",
    output_name: "CloudSignedExample.ipa"
  )
end

lane :github_release do

  version = sh("cd ..; agvtool what-version -terse").gsub("\n",'')

  set_github_release(
    repository_name: ENV["REPO"],
    api_bearer: ENV["GITHUB_TOKEN"],
    name: "v#{version}",
    tag_name: "v#{version}",
    commitish: "main",
    upload_assets: ["CloudSignedExample.ipa", "CloudSignedExample.app.dSYM.zip"]
  )
end

lane :github_release_from_xcode_cloud do
  version = sh("cd ..; agvtool what-version -terse").gsub("\n",'')
  set_github_release(
    repository_name: ENV["REPO"],
    api_bearer: ENV["GITHUB_TOKEN"],
    name: "v#{version}",
    tag_name: "v#{version}",
    commitish: "xcode-cloud-test",
    upload_assets: [ENV["CI_DEVELOPMENT_SIGNED_APP_PATH"]]
  )
end
