name: Release

on: workflow_dispatch
env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

jobs:
  release_github:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2

      - name: Bundle install
        run: bundle install

      - name: Prepare API_KEY
        env:
          AUTHENTICATION_KEY_CONTENT: ${{ secrets.AUTHENTICATION_KEY_CONTENT }}
        run: echo "$AUTHENTICATION_KEY_CONTENT" > AuthKey.p8

      - name: Build app
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          AUTHENTICATION_KEY_ISSUER_ID: ${{ secrets.AUTHENTICATION_KEY_ISSUER_ID }}
          AUTHENTICATION_KEY_ID: ${{ secrets.AUTHENTICATION_KEY_ID }}
          AUTHENTICATION_KEY_CONTENT: ${{ secrets.AUTHENTICATION_KEY_CONTENT }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: bundle exec fastlane release_to_ipa

      - name: Cleanup API_KEY
        if: always()
        run: rm -rf AuthKey.p8

      - name: Release
        env:
          LC_ALL: en_US.UTF-8
          LANG: en_US.UTF-8
          REPO: alexandre-pod/CloudSignedExample
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec fastlane github_release
